#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyHealthAndroid.Resource", IsApplication=true)]

namespace MyHealthAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InsightsCore.Resource.String.ApplicationName = global::MyHealthAndroid.Resource.String.ApplicationName;
			global::Xamarin.InsightsCore.Resource.String.Hello = global::MyHealthAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050002
			public const int btn_pressed = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int red_opaque = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int white_opaque = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a_minus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int a_plus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ab_minus = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ab_plus = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int arrow_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int arrow_top = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int arrow_top2nd = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int b_minus = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int b_plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blood = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int blood2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bmi = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int BMI_chart = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bmi_status = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int buttons_states = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Cancer = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Contact = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Default_2x = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int donor = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int donorOld = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int drop_down_new = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int dropDown = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Dropdown2 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ecard = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int edit = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int emergency = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int emergency1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int Feedback = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int feedback2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int fourm = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int grey_arrow_down = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int grey_arrow_right = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int heartfo = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int help = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int hospitals = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_launcher = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon114 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon120 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon57 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_60_2x = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ihf = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int irish_blood_trans = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int irish_heart_foundation = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int IrishHealth = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int IrishTimes = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int map_large = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int more = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int My_Profile = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int news_updates = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int NewsHealth = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Next = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int o_minus = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int o_plus = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int organ = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int organisations = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int organNotready = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int PartAIBTS = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int PartBIBTS = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int PULSE = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int RCSI = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int RCSI1 = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int RCSI_Front_Building_1 = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int RCSISplash320x480 = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int RCSISplash640x1136 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int RCSISplash640x960 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int Search = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int Search1 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int search_small = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int settings_top = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int share = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int sync = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int useful = 2130837575;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080045
			public const int abminusLabel = 2131230789;
			
			// aapt resource value: 0x7f080042
			public const int abplusLabel = 2131230786;
			
			// aapt resource value: 0x7f08006a
			public const int action_profile = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int action_sync = 2131230827;
			
			// aapt resource value: 0x7f080034
			public const int actualNews = 2131230772;
			
			// aapt resource value: 0x7f080013
			public const int addContactButton = 2131230739;
			
			// aapt resource value: 0x7f08005c
			public const int ageComponentLayout = 2131230812;
			
			// aapt resource value: 0x7f08005e
			public const int ageSpinner = 2131230814;
			
			// aapt resource value: 0x7f080044
			public const int aminusLabel = 2131230788;
			
			// aapt resource value: 0x7f080041
			public const int aplusLabel = 2131230785;
			
			// aapt resource value: 0x7f08000d
			public const int atozButton = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int backButton = 2131230722;
			
			// aapt resource value: 0x7f080038
			public const int bloodDonationLabel = 2131230776;
			
			// aapt resource value: 0x7f080046
			public const int bloodDonationLink = 2131230790;
			
			// aapt resource value: 0x7f080064
			public const int bloodGroupSpinner = 2131230820;
			
			// aapt resource value: 0x7f080062
			public const int bloodgroupComponentLayout = 2131230818;
			
			// aapt resource value: 0x7f08003f
			public const int bminusLabel = 2131230783;
			
			// aapt resource value: 0x7f08000c
			public const int bottomButtons = 2131230732;
			
			// aapt resource value: 0x7f08003c
			public const int bplusLabel = 2131230780;
			
			// aapt resource value: 0x7f080065
			public const int buttonsComponentLayout = 2131230821;
			
			// aapt resource value: 0x7f080067
			public const int calculateBMIButton = 2131230823;
			
			// aapt resource value: 0x7f08000e
			public const int categoriesButton = 2131230734;
			
			// aapt resource value: 0x7f080017
			public const int contactNameInput = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int contactNumberInput = 2131230744;
			
			// aapt resource value: 0x7f080059
			public const int countryComponentLayout = 2131230809;
			
			// aapt resource value: 0x7f08005b
			public const int countrySpinner = 2131230811;
			
			// aapt resource value: 0x7f080004
			public const int diseaseDetailImage = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int diseaseDetailWebView = 2131230725;
			
			// aapt resource value: 0x7f080009
			public const int diseaseList = 2131230729;
			
			// aapt resource value: 0x7f080029
			public const int emergencyInfo = 2131230761;
			
			// aapt resource value: 0x7f080016
			public const int emergencyList = 2131230742;
			
			// aapt resource value: 0x7f080028
			public const int emergencyName = 2131230760;
			
			// aapt resource value: 0x7f08002a
			public const int emergencyNumber = 2131230762;
			
			// aapt resource value: 0x7f08000b
			public const int expandableDiseaseList = 2131230731;
			
			// aapt resource value: 0x7f080049
			public const int feedbackUserEmail = 2131230793;
			
			// aapt resource value: 0x7f08004a
			public const int feedbackUserMessage = 2131230794;
			
			// aapt resource value: 0x7f080048
			public const int feedbackUserName = 2131230792;
			
			// aapt resource value: 0x7f080037
			public const int firstLine = 2131230775;
			
			// aapt resource value: 0x7f08001c
			public const int frameLayout2 = 2131230748;
			
			// aapt resource value: 0x7f08005f
			public const int genderComponentLayout = 2131230815;
			
			// aapt resource value: 0x7f080061
			public const int genderSpinner = 2131230817;
			
			// aapt resource value: 0x7f08001f
			public const int healthNewsBtn = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int healthProfessionalBtn = 2131230749;
			
			// aapt resource value: 0x7f080012
			public const int healthProfessionalList = 2131230738;
			
			// aapt resource value: 0x7f080007
			public const int healthProfessionalsList = 2131230727;
			
			// aapt resource value: 0x7f08001b
			public const int healthSearchBtn = 2131230747;
			
			// aapt resource value: 0x7f080052
			public const int heightComponentLayout = 2131230802;
			
			// aapt resource value: 0x7f080053
			public const int heightFeetSpinner = 2131230803;
			
			// aapt resource value: 0x7f080054
			public const int heightInchSpinner = 2131230804;
			
			// aapt resource value: 0x7f080020
			public const int helpBtn = 2131230752;
			
			// aapt resource value: 0x7f080010
			public const int helpDataList = 2131230736;
			
			// aapt resource value: 0x7f080026
			public const int helpIcon = 2131230758;
			
			// aapt resource value: 0x7f08002e
			public const int hpContactName = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int hpContactNumber = 2131230767;
			
			// aapt resource value: 0x7f080025
			public const int hpDisplayName = 2131230757;
			
			// aapt resource value: 0x7f080030
			public const int hpEditContactImage = 2131230768;
			
			// aapt resource value: 0x7f080024
			public const int hpImageView = 2131230756;
			
			// aapt resource value: 0x7f080011
			public const int hpUsefulContactList = 2131230737;
			
			// aapt resource value: 0x7f080006
			public const int imageButton1 = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int imageView1 = 2131230720;
			
			// aapt resource value: 0x7f08003b
			public const int imageView2 = 2131230779;
			
			// aapt resource value: 0x7f080021
			public const int impNotice = 2131230753;
			
			// aapt resource value: 0x7f08004c
			public const int linearLayout1 = 2131230796;
			
			// aapt resource value: 0x7f080050
			public const int matricToggleButton = 2131230800;
			
			// aapt resource value: 0x7f080036
			public const int newsChannelName = 2131230774;
			
			// aapt resource value: 0x7f080032
			public const int newsDate = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int newsFeedLayout = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int newsHeadline = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int newsImageView = 2131230773;
			
			// aapt resource value: 0x7f08003e
			public const int ominusLabel = 2131230782;
			
			// aapt resource value: 0x7f08003a
			public const int oplusLabel = 2131230778;
			
			// aapt resource value: 0x7f08004d
			public const int organDonationWebView = 2131230797;
			
			// aapt resource value: 0x7f08002b
			public const int orgnisationName = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int orgnisationNumber = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int orgnisationWebsite = 2131230765;
			
			// aapt resource value: 0x7f08000f
			public const int recentButton = 2131230735;
			
			// aapt resource value: 0x7f080047
			public const int relativeLayout1 = 2131230791;
			
			// aapt resource value: 0x7f080043
			public const int rowfour = 2131230787;
			
			// aapt resource value: 0x7f080039
			public const int rowone = 2131230777;
			
			// aapt resource value: 0x7f080040
			public const int rowthree = 2131230784;
			
			// aapt resource value: 0x7f08003d
			public const int rowtwo = 2131230781;
			
			// aapt resource value: 0x7f08004b
			public const int saveFeedback = 2131230795;
			
			// aapt resource value: 0x7f080066
			public const int saveProfileButton = 2131230822;
			
			// aapt resource value: 0x7f08004e
			public const int scrollView1 = 2131230798;
			
			// aapt resource value: 0x7f08000a
			public const int searchOptions = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int searchText = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int shareButton = 2131230723;
			
			// aapt resource value: 0x7f080014
			public const int simpleDetailImage = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int simpleWebView = 2131230741;
			
			// aapt resource value: 0x7f080069
			public const int syncButton = 2131230825;
			
			// aapt resource value: 0x7f080019
			public const int tableButtons = 2131230745;
			
			// aapt resource value: 0x7f08001a
			public const int tableRow1 = 2131230746;
			
			// aapt resource value: 0x7f080068
			public const int testlayoutforawhile = 2131230824;
			
			// aapt resource value: 0x7f08004f
			public const int textView1 = 2131230799;
			
			// aapt resource value: 0x7f080051
			public const int textView2 = 2131230801;
			
			// aapt resource value: 0x7f08001e
			public const int textView3 = 2131230750;
			
			// aapt resource value: 0x7f080056
			public const int textView4 = 2131230806;
			
			// aapt resource value: 0x7f08005a
			public const int textView5 = 2131230810;
			
			// aapt resource value: 0x7f08005d
			public const int textView6 = 2131230813;
			
			// aapt resource value: 0x7f080060
			public const int textView7 = 2131230816;
			
			// aapt resource value: 0x7f080063
			public const int textView8 = 2131230819;
			
			// aapt resource value: 0x7f080027
			public const int title = 2131230759;
			
			// aapt resource value: 0x7f080001
			public const int txtAppTitle = 2131230721;
			
			// aapt resource value: 0x7f080023
			public const int txtHeader = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int txtSmall = 2131230754;
			
			// aapt resource value: 0x7f080055
			public const int weightComponentLayout = 2131230805;
			
			// aapt resource value: 0x7f080058
			public const int weightGramSpinner = 2131230808;
			
			// aapt resource value: 0x7f080057
			public const int weightKiloSpinner = 2131230807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar_custom = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_custom_home = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_disease_details = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_health_professionals = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_health_search = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_help_data = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_hp_details_contacts = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_hp_details_simple = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_hp_details_table = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int alertview_custom_layout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Home = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Launch = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ListChild = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int ListHeader = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int row_health_professionals_table = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int row_help_table = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int row_hp_emergency = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int row_hp_orgnisation = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int row_hp_useful_numbers = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int row_news_details_table = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int row_news_table = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SimpleListItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int sub_activity_blood_donation = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int sub_activity_feedback = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int sub_activity_mybmi = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int sub_activity_organ_donation = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int sub_activity_profile = 2130903066;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int main_activity_actions = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int main_activity_actions_with_sync = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int app_name = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int hello = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int profile_text = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int sync_text = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CustomActionBar = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int MyHealthTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
