// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using Foundation;
using UIKit;
using MyHealthDB;
using MyHealthDB.Logger;
using MyHealthDB.Helper;

namespace RCSI
{
	public partial class AboutRCSIController : UIViewController
	{
		public AboutRCSIController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			await LogManager.Log<LogUsage> (new LogUsage (){
				Date = DateTime.Now,
				Page = Convert.ToInt32(Pages.MyUsefulNumbers)
			});

			AboutUs aboutus = await MyHealthDB.DatabaseManager.SelectAboutUs (0);
			string htmlString = Helper.BuildHtmlForAboutUs(aboutus);
			 
			//webView.LoadDataWithBaseURL ("file:///android_asset/", htmlString, "text/html", "utf-8", null);

			//String fileName = "Content/AboutRCSI.html";
			//String localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);
			string contentDirectoryPath = Path.Combine (NSBundle.MainBundle.BundlePath, "Content/");
			webview.LoadHtmlString(htmlString, new NSUrl(contentDirectoryPath, true));
			//webview.LoadRequest (new NSUrlRequest (new NSUrl(localHtmlUrl, false)));
			webview.ScalesPageToFit = false;

			imageView.Image = UIImage.LoadFromData (NSData.FromArray (aboutus.mainImage));//UIImage.FromFile ("images/RCSI_Front_Building_1.jpg");
			imageView.ContentMode = UIViewContentMode.ScaleAspectFit;
			//webview.BackgroundColor = UIColor.Clear;
			//webview.Opaque = false;
			//webview.InsertSubview (new UIImageView(UIImage.FromBundle("images/RCSI_Front_Building_1.jpg")),0);
			//webview.BackgroundColor = UIColor.FromPatternImage (UIImage.FromFile ("images/RCSI_Front_Building_1.jpg"));

		}
	}
}
