// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class BloodDonationController : UIViewController
	{
		public BloodDonationController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad() {
			base.ViewDidLoad ();
			await LogManager.Log<LogUsage> (new LogUsage (){ 
				Date = DateTime.Now, 
				Page = Convert.ToInt32(Pages.BloodDonation)
			});

			IList<BloodSupply> bloodSupplyList;
			if (await HelperMethods.CheckIfInternetAvailable()) {
				try {
					bloodSupplyList = await ServiceConsumer.GetBloodDonationInfo ("http://www.giveblood.ie/clinicsxml.aspx?blood=1");
					// adding new item for fetch date from service to be displayed in label
					bloodSupplyList.Add(new BloodSupply { BloodGroup = "FETCHDATE", SupplyDays = DateTime.Now.Date.ToString("dd MMM yyyy") });
					HelperMethods.SaveBloodSupply (bloodSupplyList);
				} catch {
					bloodSupplyList = HelperMethods.GetBloodSupply ();
				}
			} else {
				bloodSupplyList = HelperMethods.GetBloodSupply ();
			}
			foreach (var bloodSupply in bloodSupplyList) {
				switch (bloodSupply.BloodGroup.ToUpper ()) {
				case "O+":
					oPlus.Text = bloodSupply.SupplyDays;
					break;
				case "O-":
					oMinus.Text = bloodSupply.SupplyDays;
					break;
				case "A+":
					aPlus.Text = bloodSupply.SupplyDays;
					break;
				case "A-":
					aMinus.Text = bloodSupply.SupplyDays;
					break;
				case "B+":
					bPlus.Text = bloodSupply.SupplyDays;
					break;
				case "B-":
					bMinus.Text = bloodSupply.SupplyDays;
					break;
				case "AB+":
					abPlus.Text = bloodSupply.SupplyDays;
					break;
				case "AB-":
					abMinus.Text = bloodSupply.SupplyDays;
					break;

				case "FETCHDATE":
					lblDateMessage.Text = String.Format ("Refreshed on {0}", bloodSupply.SupplyDays);
					break;
				}
			}
		}

		partial void goToIBTSSite (UIKit.UIButton sender)
		{
			UIApplication.SharedApplication.OpenUrl(NSUrl.FromString("http://www.giveblood.ie"));
		}
	}
}
