// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;

using Foundation;
using UIKit;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class EmergencyController : UIViewController
	{
		public bool IsVideos
		{
			get;
			set;
		}

		public int MediaCategoryId
		{
			get;
			set;
		}

		private EmergencyContactSource _emergencyContactSource;
		public EmergencyController (IntPtr handle) : base (handle)
		{
		}

		async public override void ViewDidLoad() {
			base.ViewDidLoad ();

			await LogManager.Log<LogUsage> (new LogUsage (){
				Date = DateTime.Now,
				Page = Convert.ToInt32(Pages.Emergency)
			});

			if (IsVideos)
			{
				var videoLinksTableSource = new VideoLinksSource(this);
				videoLinksTableSource._items = await DatabaseManager.GetVideoLinksAsync($"{MediaCategoryId}");

				this.tableView.Source = videoLinksTableSource;
			}
			else
			{
				_emergencyContactSource = new EmergencyContactSource(this);
				_emergencyContactSource._items = await DatabaseManager.SelectAllEmergencyContacts();
				this.tableView.Source = _emergencyContactSource;
			}

			this.tableView.ReloadData ();

			/*UITapGestureRecognizer gestureRecognizer = new UITapGestureRecognizer (HideKeyboard);
			this.tableView.AddGestureRecognizer (gestureRecognizer);*/

			//this.tableView.Scrolled += (sender, e) => this.searchBar.ResignFirstResponder ();
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);
		}
	}

	public class EmergencyContactSource : UITableViewSource
	{
		public List<EmergencyContacts> _items;// = new String[,] {{"Emergency","Emergency police Fire Ambulance", "112"}, {"KDOC","Kildare and West Wicklow Doctors on Call", "1890 599 362"},
			//{"NEDOC","North East Doctor on Call", "1890 777 911"}, {"SouthDoc","Cork and Kerry", "1850 335 999"}};
		public List<EmergencyContacts> SearchItems;
		EmergencyController _controller;
		public EmergencyContactSource (EmergencyController controller)
		{
			_controller = controller;
		}

		public override nint NumberOfSections (UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection (UITableView tableView, nint section)
		{
			return _items.Count;
		}

		static String cellIdentifier = "EmergencyCell";
		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			EmergencyTableViewCell cell = null;
			cell = tableView.DequeueReusableCell (cellIdentifier) as EmergencyTableViewCell;
			// if there are no cells to reuse, create a new one
			if (cell == null) {
				cell = new EmergencyTableViewCell (UITableViewCellStyle.Default, cellIdentifier);
				cell.Accessory = UITableViewCellAccessory.DisclosureIndicator;
			}
			cell.UpdateCell (_items.ElementAt (indexPath.Row));

			return cell;
		}

		public override void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			//_controller.HideKeyboard ();
			//_controller.PerformSegue ("Details", tableView);
			//tableView.DeselectRow (indexPath, true);
		}
	}

	public class VideoLinksSource : UITableViewSource
	{
		public List<VideoLink> _items;
		EmergencyController _controller;
		public VideoLinksSource(EmergencyController controller)
		{
			_controller = controller;
		}

		public override nint NumberOfSections(UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return _items.Count;
		}

		static String cellIdentifier = "EmergencyCell";
		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			EmergencyTableViewCell cell = null;
			cell = tableView.DequeueReusableCell(cellIdentifier) as EmergencyTableViewCell;
			// if there are no cells to reuse, create a new one
			if (cell == null)
			{
				cell = new EmergencyTableViewCell(UITableViewCellStyle.Default, cellIdentifier);
				cell.Accessory = UITableViewCellAccessory.DisclosureIndicator;
			}
			cell.UpdateCell(_items.ElementAt(indexPath.Row));

			return cell;
		}

		public override void RowSelected(UITableView tableView, NSIndexPath indexPath)
		{
		}
	}
}
