// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RCSI
{
	public partial class FeedbackTableViewController : UITableViewController
	{
		public FeedbackTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
