// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RCSI.MyHealth
{
	public partial class HealthServicesTableViewController : UITableViewController
	{
		public HealthServicesTableViewController (IntPtr handle) : base (handle)
		{
		}

		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);
		}
	}
}
