// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Threading.Tasks;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class HomeController : UIViewController
	{
		Boolean FirstTimeInstall;

		public HomeController (IntPtr handle) : base (handle)
		{
		}

		partial void begin_clicked (UIButton sender)
		{
		}

		partial void contacts_clicked (UIButton sender)
		{
		}

		partial void myProfile_clicked (UIButton sender)
		{
		}

		partial void next_clicked (UIButton sender)
		{
		}

		public async override void ViewDidLoad() {
			base.ViewDidLoad ();
			FirstTimeInstall = NSUserDefaults.StandardUserDefaults.BoolForKey ("MyHealthFirstInstall");
			if (!FirstTimeInstall) {
				UIApplication.SharedApplication.NetworkActivityIndicatorVisible = true;

				await MyHealthDB.ServiceConsumer.SyncDevice ();

				UIApplication.SharedApplication.NetworkActivityIndicatorVisible = false;
			}

			await LogManager.Log<LogUsage> (new LogUsage (){ 
				Date = DateTime.Now, 
				Page = Convert.ToInt32(Pages.Home)
			});
		}

		partial void goBack (UIButton sender)
		{
			this.NavigationController.PopViewControllerAnimated(true);
		}
	}
}
