// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace RCSI
{
	public partial class HospitalsMapController : UIViewController
	{
		public HospitalsMapController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.imageView.Image = UIImage.FromBundle ("images/map_large.jpg");
			UITapGestureRecognizer imageTap = new UITapGestureRecognizer (() => {

				PerformSegue("hospitalDetailsSegue",this);

			});

			this.imageView.UserInteractionEnabled = true;
			this.imageView.AddGestureRecognizer (imageTap);

		}
	}
}
