// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using System.Threading.Tasks;

using Foundation;
using UIKit;

using MyHealthDB;

namespace RCSI
{
	public partial class HospitalsMapController : UIViewController
	{
		private int _provinceId;

		public HospitalsMapController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

//			this.imageView.Image = UIImage.FromBundle ("images/map_large.jpg");
//			UITapGestureRecognizer imageTap = new UITapGestureRecognizer (() => {
//
//				PerformSegue("hospitalDetailsSegue",this);
//
//			});
//
//			this.imageView.UserInteractionEnabled = true;
//			this.imageView.AddGestureRecognizer (imageTap);

			String localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, "Provinces.html");
			webView.LoadRequest (new NSUrlRequest (new NSUrl (localHtmlUrl, false)));
//
//			webView.ScalesPageToFit = false;
			webView.ShouldStartLoad = HandleShouldStartLoad;
		}

		public bool HandleShouldStartLoad(UIWebView webView, NSUrlRequest request, UIWebViewNavigationType navigationType)
		{
			// you need to implement this method depending on your criteria
			if (navigationType.Equals(UIWebViewNavigationType.LinkClicked))
			{
				var provinceName = request.Url.Query;
				DatabaseManager.SelectProvince (provinceName)
					.ContinueWith((r) => {
						_provinceId = r.Result.ID.Value;
						PerformSegue("hospitalDetailsSegue", this);
					}, TaskScheduler.FromCurrentSynchronizationContext());

				return false;
			}

			// this.OpenInExternalBrowser(request) returned false -> let the UIWebView load the request
			return true;
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if (segue.Identifier == "hospitalDetailsSegue") {
				var destCont = (HospitalsController)segue.DestinationViewController;
				destCont.ProvinceId = _provinceId;
			}
		}
	}
}
