// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RCSI
{
	public partial class HospitalsTableViewCell : UITableViewCell
	{
		public HospitalsTableViewCell (IntPtr handle) : base (handle)
		{
		}

		public HospitalsTableViewCell(UITableViewCellStyle style,string cellidentifier) : base(style,cellidentifier)
		{

		}

		public void UpdateCell(string name, string tel,string website)
		{
			lblName.Text = name;
			btnWebsite.SetTitle( "Website: " + website, UIControlState.Normal);
			btnTel.TouchUpInside += DialNumber;
			btnTel.SetTitle( "Tel: " + tel, UIControlState.Normal);

		}

		public void DialNumber(object sender, EventArgs e)
		{
			string number = ((UIButton)sender).Title (UIControlState.Normal).Replace("Tel: ","").Trim().Replace (" ", "");
			if(!string.IsNullOrEmpty(number))
				UIApplication.SharedApplication.OpenUrl (new NSUrl ("tel:" + number));
		}
	}
}
