// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RCSI
{
	public partial class NavBarController : UIViewController
	{
		public NavBarController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			if (this.ParentViewController != null) {
				lblTitle.Text = this.ParentViewController.Title;
			}
		}

		partial void goBack (UIButton sender)
		{
			this.ParentViewController.NavigationController.PopViewController(true);
		}

		partial void btnShareClicked (NSObject sender)
		{
			if (this.ParentViewController.GetType().Equals(typeof(IllnessDetailsController))) {
				((IllnessDetailsController)this.ParentViewController).btnShareClick();
			}
		}
	}
}
