// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class NewsController : UITableViewController
	{
		public NewsController (IntPtr handle) : base (handle)
		{
		}

		public override async void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			await LogManager.Log<LogUsage> (new LogUsage (){ 
				Date = DateTime.Now, 
				Page = Convert.ToInt32(Pages.HealthNews)
			});
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			var controller = segue.DestinationViewController as BBCNewsFeedController;
		
			if (controller != null) 
			{
				switch (segue.Identifier.ToLower()) {
				case "bbc":
					controller.SelectedRssFeedType = RssFeedType.BBCNews;
					controller.Title = "BBC Medical News";
					break;
				case "pulse":
					controller.SelectedRssFeedType = RssFeedType.PulseVoices;
					controller.Title = "Pulse News";
					break;
				case "irishhealth":
					controller.SelectedRssFeedType = RssFeedType.IrishHealth;
					controller.Title = "Irish Health News";
					break;
				case "irishtimes":
					controller.SelectedRssFeedType = RssFeedType.irishTimes;
					controller.Title = "Irish Times News";
					break;

				}

			}

//			if (segue.Identifier == "") {
//				destinationController.SelectedRssFeedType = RssFeedType.IrishHealth;
//			}
		}
	}
}
