// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class NewsController : UITableViewController
	{
		public NewsController (IntPtr handle) : base (handle)
		{
		}

		public override async void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			await LogManager.Log<LogUsage> (new LogUsage (){ 
				Date = DateTime.Now, 
				Page = Convert.ToInt32(Pages.HealthNews)
			});
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);
			var destinationController = (BBCNewsFeedController)sender;
			destinationController.SelectedRssFeedType = RssFeedType.BBCNews;
//			if (segue.Identifier == "") {
//				destinationController.SelectedRssFeedType = RssFeedType.IrishHealth;
//			}
		}
	}
}
