// This file has been autogenerated from a class added in the UI designer.

using System;
using System.IO;
using Foundation;
using UIKit;

using MyHealthDB;
using MyHealthDB.Logger;

namespace RCSI
{
	public partial class OrganDonationsController : UIViewController
	{
		public OrganDonationsController (IntPtr handle) : base (handle)
		{
		}

		public override async void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.Title = "Organ Donations";
			await LogManager.Log<LogUsage> (new LogUsage (){ 
				Date = DateTime.Now, 
				Page = Convert.ToInt32(Pages.OrganDonors)
			});

			String fileName = "Content/OrganDonor.html";
			String localHtmlUrl = Path.Combine (NSBundle.MainBundle.BundlePath, fileName);
			webView.LoadRequest (new NSUrlRequest (new NSUrl(localHtmlUrl, false)));
			webView.ScalesPageToFit = false;
		}

	}
}
